config/routes.rb
Airlifteauto::Application.routes.draw do
  resources :adresses

  resources :posts

end

app/models/adress.rb
class Adress < ActiveRecord::Base
  attr_accessible :adress
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :from, :to
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  # GET /adresses
  # GET /adresses.json
  def index
    @adresses = Adress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adresses }
    end
  end

  # GET /adresses/1
  # GET /adresses/1.json
  def show
    @adress = Adress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @adress }
    end
  end

  # GET /adresses/new
  # GET /adresses/new.json
  def new
    @adress = Adress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @adress }
    end
  end

  # GET /adresses/1/edit
  def edit
    @adress = Adress.find(params[:id])
  end

  # POST /adresses
  # POST /adresses.json
  def create
    @adress = Adress.new(params[:adress])

    respond_to do |format|
      if @adress.save
        format.html { redirect_to @adress, notice: 'Adress was successfully created.' }
        format.json { render json: @adress, status: :created, location: @adress }
      else
        format.html { render action: "new" }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adresses/1
  # PUT /adresses/1.json
  def update
    @adress = Adress.find(params[:id])

    respond_to do |format|
      if @adress.update_attributes(params[:adress])
        format.html { redirect_to @adress, notice: 'Adress was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adresses/1
  # DELETE /adresses/1.json
  def destroy
    @adress = Adress.find(params[:id])
    @adress.destroy

    respond_to do |format|
      format.html { redirect_to adresses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/adresses/_form.html.erb
<%= form_for(@adress) do |f| %>
  <% if @adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
      <% @adress.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :adress %><br />
    <%= f.text_field :adress %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adresses/edit.html.erb
<h1>Editing adress</h1>

<%= render 'form' %>

<%= link_to 'Show', @adress %> |
<%= link_to 'Back', adresses_path %>

app/views/adresses/index.html.erb
<h1>Listing adresses</h1>

<table>
  <tr>
    <th>Adress</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adresses.each do |adress| %>
  <tr>
    <td><%= adress.adress %></td>
    <td><%= link_to 'Show', adress %></td>
    <td><%= link_to 'Edit', edit_adress_path(adress) %></td>
    <td><%= link_to 'Destroy', adress, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adress', new_adress_path %>

app/views/adresses/new.html.erb
<h1>New adress</h1>

<%= render 'form' %>

<%= link_to 'Back', adresses_path %>

app/views/adresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Adress:</b>
  <%= @adress.adress %>
</p>


<%= link_to 'Edit', edit_adress_path(@adress) %> |
<%= link_to 'Back', adresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airlifteauto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
    <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to, :class => 'address-picker-input' %>
    </div>

	<!-- ============================================================================ -->
to
	<div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from, :class => 'address-picker-input' %>
	</div>
<script type="text/javascript">

        //AddressPickerRails.Pickers.applyOnReady({
        //    'onLoad':function (railsPicker) {
        //        console.debug("callback for a single pond with ID '%s'", railsPicker.getIdPrefix());
        //    }
        //});

        AddressPickerRails.Pickers.apply({
            'onLoad':function (railsPicker) {
                console.debug("callback for a single pond with ID '%s'", railsPicker.getIdPrefix());
            }
        });
    </script>

	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.from %></td>
    <td><%= post.to %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @post.from %>
</p>

<p>
  <b>To:</b>
  <%= @post.to %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>